### ISSUE TITLE
Use a one-proportion z-test instead of a chi-square

### ISSUE THREAD

**Issue by lukasvermeer** [lukasvermeer/srm#56]
@keesmulder suggested we should use a one-proportion z-test instead of a chi-square.

For example:
```
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

stats.chisquare([502,498],[500,500])[1]
proportions_ztest(count=502, nobs=1000, value=0.5)[1]
stats.chisquare([502,498],[500,500])[1] - proportions_ztest(count=502, nobs=1000, value=0.5)[1]

stats.chisquare([600,400],[500,500])[1]
proportions_ztest(count=400, nobs=1000, value=0.5)[1]
stats.chisquare([600,400],[500,500])[1] -proportions_ztest(count=400, nobs=1000, value=0.5)[1]
```

Which yields:
```
python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import stats
>>> from statsmodels.stats.proportion import proportions_ztest
>>> 
>>> stats.chisquare([502,498],[500,500])[1]
0.8993431885613663
>>> proportions_ztest(count=502, nobs=1000, value=0.5)[1]
0.8993423875828498
>>> stats.chisquare([502,498],[500,500])[1] - proportions_ztest(count=502, nobs=1000, value=0.5)[1]
8.009785165130623e-07
>>> 
>>> stats.chisquare([600,400],[500,500])[1]
2.5396285894708634e-10
>>> proportions_ztest(count=400, nobs=1000, value=0.5)[1]
1.082387390934913e-10
>>> stats.chisquare([600,400],[500,500])[1] -proportions_ztest(count=400, nobs=1000, value=0.5)[1]
1.4572411985359504e-10
```

At first glance, this seems to be more sensitive.

Maybe @geoprofi has an opinion here too?

**Comment by lukasvermeer** [comment]
The [js library](https://github.com/lukasvermeer/srm/blob/master/chrome-extension/src/lib/statistics-distributions.js) we are using does not seem to support proportions_ztest, so we would have to find one that does, or implement from scratch.

**Comment by keesmulder** [comment]
I've had a review of  the [code that does the test](https://github.com/lukasvermeer/srm/blob/9ee4e01d576696a75e6e98fa8ace5d22fca5f578/chrome-extension/src/srm.js#L26), and it turns out my initial guess as to how this works was wrong. The good news is that it actually performs the right test, which I think is mathematically equivalent, or roughly equivalent, to my suggestion of the One-Proportion Z-test.

So it's mostly a verbal confusion, because many implementations of Chi-Square tests of Independence work on contingency tables directly, rather than asking for the observed and expected counts. 

The conclusion is that we could still simplify the code a bit by using the one-proportion z-test, but it won't help the power/validity of the tests enough, so I don't think it is worth the effort to implement.

**Comment by geoprofi** [comment]
The library used a z-test initially but it was replaced with the
appropriate chi-square test with reason. Happy to go over that again if
necessary, but it seems there is no need at this point?

Georgi Georgiev

https://www.linkedin.com/in/geoprofi/
+359 897 721 474
