### ISSUE TITLE
Change extension icon based on check results

### ISSUE THREAD

**Issue by lukasvermeer** [lukasvermeer/srm#6]
Rather than changing the page background to red ...

**Comment by MJBeisch** [comment]
Oh good, I was going to request something like this but I see it's already an item. As-is, since there's no "green light" to indicate no detected mismatch, as a user I'm not 100% sure the extension is functioning since it lacks that positive feedback. If you intend to keep the in-page manipulation, I'd also suggest including screenshots in the documentation for what the user "should" see (for each supported tool) under positive/negative conditions.

**Comment by lukasvermeer** [comment]
Thanks for your feedback! This is great! 🙌

> As-is, since there's no "green light" to indicate no detected mismatch, as a user I'm not 100% sure the extension is functioning since it lacks that positive feedback.

I agree this is not ideal. There is also a related improvement #5 which I think would give even more insight for users into what is happening in the background.

> If you intend to keep the in-page manipulation, 

I think we do. If we remove it, I'd worry problems are too easy to miss.

> I'd also suggest including screenshots in the documentation for what the user "should" see (for each supported tool) under positive/negative conditions.

Ah. Fair point. So far, what you "should" see is no different from what you would normally see. The extension only manipulates the page when an issue is detected.

**Comment by MJBeisch** [comment]
Very good. I checked about 10 experiments in Convert and Google Optimize and didn't see any changes, so that made me slightly question if the extension was functional. I didn't think to check an experiment with a known SRM to confirm, and would not expect a user to have a "known bad sample" on hand just to test functionality. The current screenshot of Google Optimize in the documentation does show the red highlighting, but it's scaled down to low for it to be easily understood that's what's happening. Maybe add a zoom-in + annotation to screenshots as well.

**Comment by lukasvermeer** [comment]
> I didn't think to check an experiment with a known SRM to confirm, and would not expect a user to have a "known bad sample" on hand just to test functionality.

Totally agree. I just added a basic indicator badge that should help, but requires Chrome Store review before it's live. Let me know what you think once you see it?

> The current screenshot of Google Optimize in the documentation does show the red highlighting, but it's scaled down too low for it to be easily understood that's what's happening. Maybe add a zoom-in + annotation to screenshots as well.

I'm not a designer. At all. I agree the screenshots could be a lot better.

**Comment by MJBeisch** [comment]
![SRM-Detection-Extension-Screenshot](https://user-images.githubusercontent.com/44927808/76255624-db8cbd80-6224-11ea-9052-97c48b71165d.png)

**Comment by lukasvermeer** [comment]
This was added in 934d367275fc221d39abf874e8cac5e282ec9ac7 and 5db2357ae34e7ab1624501c225c55c70ec25b808 which are already released to Store version. I just forgot to close this ticket. Oops.
